spring.application.name=weekly-report-generator
local.server.port=8080

spring.config.import=optional:classpath:application-secrets.properties

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=WARN

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=86400000
app.jwt.cookie-secure=${APP_JWT_COOKIE_SECURE}

springdoc.swagger-ui.path=/swagger-ui.html